// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sort_indices
IntegerVector sort_indices(NumericVector x);
RcppExport SEXP _tidygenomics_sort_indices(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sort_indices(x));
    return rcpp_result_gen;
END_RCPP
}
// cluster_interval
IntegerVector cluster_interval(NumericVector starts, NumericVector ends, int max_distance);
RcppExport SEXP _tidygenomics_cluster_interval(SEXP startsSEXP, SEXP endsSEXP, SEXP max_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< int >::type max_distance(max_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(cluster_interval(starts, ends, max_distance));
    return rcpp_result_gen;
END_RCPP
}
